name: Prettier

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install prettier
        run: |
          echo "{}" | tee package.json
          corepack enable
          YARN_ENABLE_IMMUTABLE_INSTALLS=false corepack use yarn@3
          yarn init
          yarn add prettier
 
      - name: Create files
        run: |
          x=a
          b() {
            touch $x.json && x="$x$x" || true
          }
          for c in $(seq 10); do b;done

      - name: "Run prettier (${{env.count}})"
        env: 
          count: 7
        run: |
          spec="{"$(ls a* | head -${{env.count}} |xargs| tr " " ,)"}"
          (
            echo "spec: $spec"
            eval ls $spec
            yarn prettier "$spec" 2>&1
          ) | tee -a $GITHUB_STEP_SUMMARY

      - name: "Run prettier (${{env.count}})"
        env: 
          count: 8
        run: |
          spec="{"$(ls a* | head -${{env.count}} |xargs| tr " " ,)"}"
          (
            echo "spec: $spec"
            eval ls $spec
            strace -ff -s2048 yarn prettier "$spec" 2>&1
          ) | tee -a $GITHUB_STEP_SUMMARY
